/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "ReactNativeTurboSqliteJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeTurboSqliteCxxSpecJSI_openDatabase(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeTurboSqliteCxxSpecJSI *>(&turboModule)->openDatabase(
    rt,
    (count > 0 || (throw jsi::JSError(rt, "Expected argument in position 0 to be passed"), false), args[0].asString(rt)),
    count <= 1 || args[1].isUndefined() ? std::nullopt : std::make_optional(args[1].asString(rt))
  );
}
static jsi::Value __hostFunction_NativeTurboSqliteCxxSpecJSI_getVersionString(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeTurboSqliteCxxSpecJSI *>(&turboModule)->getVersionString(
    rt
  );
}

NativeTurboSqliteCxxSpecJSI::NativeTurboSqliteCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("TurboSqliteCxx", jsInvoker) {
  methodMap_["openDatabase"] = MethodMetadata {2, __hostFunction_NativeTurboSqliteCxxSpecJSI_openDatabase};
  methodMap_["getVersionString"] = MethodMetadata {0, __hostFunction_NativeTurboSqliteCxxSpecJSI_getVersionString};
}


} // namespace facebook::react
